'use client';

import {
  Lock,
  Wifi,
  GitBranch,
  Key,
  Server,
  Eye,
  FileText,
  Award,
  Mail,
  Shield,
  ChevronDown,
} from 'lucide-react';
import { useState } from 'react';

import { LuxShell } from '@/components/lux/chrome';
import { FadeUp, Stagger, StaggerItem } from '@/components/lux/motion';
import { FAQS } from '@/components/security/faqs';

import type { LucideIcon } from 'lucide-react';

/* ── status tag ─────────────────────────────────────────────────── */

function Status({ kind }: { kind: 'active' | 'roadmap' }) {
  return (
    <span
      className={`font-dmmono text-[9px] uppercase tracking-[0.16em] ${
        kind === 'active' ? 'text-gold' : 'text-amber-400/80'
      }`}
    >
      {kind === 'active' ? 'Active in production' : 'On roadmap'}
    </span>
  );
}

/* ── data ───────────────────────────────────────────────────────── */

type Badge = {
  icon: LucideIcon;
  label: string;
  title: string;
  desc: string;
  status: 'active' | 'roadmap';
};

const BADGES: Badge[] = [
  {
    icon: Lock,
    label: 'At-Rest Encryption',
    title: 'AES-256',
    status: 'active',
    desc: 'Database fields containing personal data, identity documents, and financial records are encrypted with AES-256. Verification documents are held in private Supabase Storage buckets — never in public object storage.',
  },
  {
    icon: Wifi,
    label: 'In-Transit Encryption',
    title: 'TLS 1.3',
    status: 'active',
    desc: 'All connections are served over modern TLS (1.3 negotiated where the client supports it). Legacy TLS 1.0/1.1 are not offered at the edge. No unencrypted data transmission is possible within the platform.',
  },
  {
    icon: GitBranch,
    label: 'Data Isolation',
    title: 'Row Level Security',
    status: 'active',
    desc: 'PostgreSQL Row Level Security enforces organisation-scoped isolation at the database query level. No organisation can read another organisation’s data — enforced by the database engine, not by application logic.',
  },
  {
    icon: Key,
    label: 'Authentication',
    title: 'Passwordless + MFA',
    status: 'roadmap',
    desc: 'Sign-in is passwordless email one-time-passcode today — no reusable passwords to phish. Mandatory TOTP-authenticator MFA for Owner, Administrator, and leadership roles is on the near-term roadmap. SMS 2FA will not be offered (SIM-swap risk).',
  },
  {
    icon: Server,
    label: 'Key Management',
    title: 'Separated Keys',
    status: 'active',
    desc: 'Encryption keys are managed by the platform key service, logically separated from the data they protect. Application secrets and service-role keys are read only server-side and are never shipped to the browser.',
  },
  {
    icon: Eye,
    label: 'Access Control',
    title: 'Verification-Gated',
    status: 'active',
    desc: 'No organisation reaches sensitive program workflows without completing verified onboarding. Role-based policies govern what each verified party can see, submit, approve, and export.',
  },
  {
    icon: FileText,
    label: 'Audit Integrity',
    title: 'Append-Only Logs',
    status: 'active',
    desc: 'Every approval, rejection, document action, admin action, and data export is written to an append-only audit log. Records cannot be edited or deleted — only new entries can be added.',
  },
  {
    icon: Award,
    label: 'Certification Roadmap',
    title: 'SOC 2 Type II',
    status: 'roadmap',
    desc: 'SOC 2 Type II audit commissioned for 2027 Q2, following a six-month continuous evidence period. Underlying providers (Vercel, Supabase) are already SOC 2 Type II audited. ISO 27001 alignment assessed alongside.',
  },
];

const ENCRYPTION = [
  {
    title: 'At rest: AES-256',
    body: 'Database fields containing personal data are encrypted with AES-256. Supabase Storage buckets holding verification documents (Emirates IDs, trade licences, professional certificates) are private — no public URL, no indexable access. Documents are served exclusively via short-lived signed URLs generated by authenticated server-side functions.',
    tech: 'Standard: AES-256 · Storage: Supabase private buckets · Access: signed URLs',
  },
  {
    title: 'In transit: TLS 1.3',
    body: 'TLS 1.3 is negotiated on all connections between client devices, the application layer, and the database, wherever the client supports it. Legacy TLS 1.0/1.1 are not offered at the Vercel and Supabase edge. HSTS is enforced with a one-year max-age and preload.',
    tech: 'Standard: TLS 1.3 · Legacy: Not offered · HSTS: max-age 31536000; preload',
  },
  {
    title: 'Key management: separated',
    body: 'Encryption keys are managed by the platform key service and are logically separated from the data they protect. Service-role credentials are read only in the server environment and never reach the browser. Column-level encryption for the most sensitive references (national ID, payment identifiers) is on the roadmap as a second layer.',
    tech: 'Keys: separated from data · Service keys: server-only · Column encryption: roadmap',
  },
];

const RLS_STANDARD = [
  'Access control enforced by application code',
  'A session-level vulnerability can bypass to another tenant’s data',
  'Penetration test must cover every application code path',
  'Audit: trace every data access through application logs',
];
const RLS_BAYTY = [
  'Access control enforced at the PostgreSQL query-planner level',
  'No application vulnerability can cross organisational data boundaries',
  'The security perimeter is the database — not the application code',
  'Audit: organisation_id scoping is enforced by the engine, not by logic',
];

const ROLES = [
  'Owner / Authority',
  'Consultant',
  'Tier-1 Contractor',
  'Subcontractor',
  'Supplier',
  'Administrator',
];
type Cell = 'yes' | 'no' | 'limited';
// create · approve · access docs · export · manage users
const MATRIX: Cell[][] = [
  ['yes', 'yes', 'yes', 'yes', 'yes'],
  ['no', 'yes', 'yes', 'limited', 'no'],
  ['limited', 'yes', 'yes', 'limited', 'limited'],
  ['no', 'no', 'limited', 'no', 'no'],
  ['no', 'no', 'limited', 'no', 'no'],
  ['yes', 'yes', 'yes', 'yes', 'yes'],
];
const MATRIX_COLS = [
  'Create projects',
  'Approve',
  'Access documents',
  'Export data',
  'Manage users',
];

const HEADERS: { name: string; value: string; desc: string; status: 'active' | 'roadmap' }[] = [
  {
    name: 'Strict-Transport-Security',
    value: 'max-age=31536000; includeSubDomains; preload',
    desc: 'Forces HTTPS for all connections. Prevents SSL stripping and protocol downgrade.',
    status: 'active',
  },
  {
    name: 'X-Frame-Options',
    value: 'DENY',
    desc: 'Prevents clickjacking via iframe embedding on any origin.',
    status: 'active',
  },
  {
    name: 'X-Content-Type-Options',
    value: 'nosniff',
    desc: 'Prevents MIME-type sniffing attacks on uploaded documents.',
    status: 'active',
  },
  {
    name: 'Content-Security-Policy',
    value: 'Report-Only (enforcing planned)',
    desc: 'Currently deployed in Report-Only mode to observe violations safely before enforcement. Enforcing CSP with no inline scripts is on the near-term roadmap.',
    status: 'roadmap',
  },
  {
    name: 'Referrer-Policy',
    value: 'strict-origin-when-cross-origin',
    desc: 'Limits referrer-header data leakage on cross-origin navigation.',
    status: 'active',
  },
  {
    name: 'Permissions-Policy',
    value: 'camera=(), microphone=(), geolocation=()',
    desc: 'Disables browser APIs the platform does not use — removes unnecessary attack surface.',
    status: 'active',
  },
];

const DOC_CONTROLS = [
  {
    title: 'Storage Isolation',
    body: 'Verification documents are stored in dedicated private Supabase Storage buckets, separated from other platform data. Bucket-level access policies are enforced independently of application logic.',
  },
  {
    title: 'No Permanent URLs',
    body: 'Verification documents have no permanent URL. Access is exclusively via signed, time-limited URLs generated by authenticated server-side functions. Documents cannot be cached, indexed, or bookmarked.',
  },
  {
    title: 'Access Logging',
    body: 'Every access to a verification document is recorded with requesting user ID, organisation ID, document type, timestamp, and access method. Logs are append-only.',
  },
  {
    title: 'Retention & Deletion',
    body: 'Active account: documents retained for the account lifecycle plus 90 days. Closed account: personal data deleted within 30 days per UAE PDPL Article 14. Deletion is automated and generates a deletion confirmation record.',
  },
  {
    title: 'Breach Protocol',
    body: 'A confirmed breach affecting verification documents triggers TDRA notification within 72 hours per UAE PDPL, with affected data subjects notified within 10 business days. The incident-response plan is reviewed quarterly.',
  },
];

const TIMELINE = [
  {
    q: '2026 Q3',
    t: 'Controls Implementation',
    b: 'Document and implement all SOC 2 Trust Service Criteria controls — Security, Availability, Confidentiality. Access-control matrix documented. Incident-response plan finalised. Vendor risk assessments completed.',
  },
  {
    q: '2026 Q4 – 2027 Q1',
    t: 'Evidence Collection Period',
    b: 'Six-month continuous compliance evidence period begins. Access logs, change-management records, security-incident logs, and availability metrics collected systematically. Internal audit conducted at midpoint.',
  },
  {
    q: '2027 Q2',
    t: 'External Audit',
    b: 'SOC 2 Type II audit commissioned with a specialist information-security auditor. Scope: Security, Availability, Confidentiality. Evidence period: 2026 Q4 – 2027 Q1.',
  },
  {
    q: '2027 Q3',
    t: 'Report Issued',
    b: 'SOC 2 Type II report issued and available to enterprise and government clients under NDA. Enables formal vendor approval for financial-services, government, and regulated-industry clients.',
  },
];

const RESIDENCY = [
  {
    region: 'EU — Frankfurt (AWS)',
    data: 'All platform data at launch: user accounts, project records, verification documents, approval history',
    status: 'Active — current default',
  },
  {
    region: 'UAE — Bahrain (AWS)',
    data: 'UAE-jurisdiction client data; preference for government and public-sector programs',
    status: 'Roadmap — Month 12',
  },
  {
    region: 'Saudi Arabia — Riyadh (AWS)',
    data: 'KSA-jurisdiction client data; required for Saudi PDPL government-program compliance',
    status: 'Roadmap — 2027 Q3',
  },
  {
    region: 'Custom residency',
    data: 'Dedicated deployment for programs requiring single-jurisdiction isolation',
    status: 'Available — enterprise negotiation',
  },
];

/* ── small helpers ──────────────────────────────────────────────── */

function Overline({ children, light }: { children: React.ReactNode; light?: boolean }) {
  return (
    <p
      className={`font-dmmono text-[11px] uppercase tracking-[0.28em] ${light ? 'text-slateink' : 'text-gold'}`}
    >
      {children}
    </p>
  );
}
function cellMark(c: Cell) {
  if (c === 'yes') return <span className="text-gold">✓</span>;
  if (c === 'limited') return <span className="text-amber-400/90">Limited</span>;
  return <span className="text-offwhite/30">—</span>;
}

/* ── page body ──────────────────────────────────────────────────── */

export default function SecurityContent() {
  const [open, setOpen] = useState<number | null>(0);

  return (
    <LuxShell>
      {/* SECTION 1 — HERO */}
      <section className="pt-[76px]">
        <div className="mx-auto w-full max-w-container px-6 py-24 md:px-10 md:pb-section md:pt-36">
          <FadeUp>
            <Overline>BaytyAI → Security</Overline>
          </FadeUp>
          <FadeUp delay={0.08} className="mt-8 max-w-[780px]">
            <h1 className="font-cormorant text-[clamp(2rem,7vw,4.5rem)] font-light leading-[1.06] tracking-[-0.01em] text-offwhite">
              When the data includes claims evidence, contractor identity, and government approvals
              —<span className="text-gold"> security is not optional.</span>
            </h1>
          </FadeUp>
          <FadeUp delay={0.16} className="mt-8 max-w-[620px]">
            <p className="font-dmsans text-lg font-light leading-relaxed text-offwhite/65 md:text-xl">
              BaytyAI is built for programs where a data breach is not a PR problem — it is a
              commercial liability and a regulatory event. Every control on this page is labelled
              with its real status: active in production, or on the roadmap.
            </p>
          </FadeUp>
          <FadeUp delay={0.24} className="mt-10 flex flex-col gap-4 sm:flex-row">
            <a
              href="mailto:enterprise@baytyai.com?subject=Security Documentation Request"
              className="inline-flex items-center justify-center gap-2 bg-gold px-7 py-3.5 font-dmmono text-[12px] uppercase tracking-[0.18em] text-navy transition-colors hover:bg-gold-soft"
            >
              Request security documentation →
            </a>
            <a
              href="/implementation"
              className="inline-flex items-center justify-center gap-2 border-[0.5px] border-gold px-7 py-3.5 font-dmmono text-[12px] uppercase tracking-[0.18em] text-gold transition-colors hover:bg-gold/10"
            >
              Review implementation model →
            </a>
          </FadeUp>
          <FadeUp delay={0.32} className="mt-12 flex flex-wrap items-center gap-x-4 gap-y-2">
            {[
              'AES-256 Encrypted',
              'TLS 1.3 In Transit',
              'Supabase RLS',
              'Passwordless Auth',
              'UAE PDPL',
              'SOC 2 Roadmap',
            ].map((t, i) => (
              <span key={t} className="flex items-center gap-4">
                {i > 0 && <span className="h-3 w-px bg-gold/40" aria-hidden />}
                <span className="font-dmmono text-[10px] uppercase tracking-[0.16em] text-offwhite/50">
                  {t}
                </span>
              </span>
            ))}
          </FadeUp>
        </div>
      </section>

      {/* SECTION 2 — 8 BADGES */}
      <section className="bg-offwhite py-24 text-navy md:py-section">
        <div className="mx-auto w-full max-w-container px-6 md:px-10">
          <FadeUp>
            <Overline light>Security Posture</Overline>
            <h2 className="mt-6 font-cormorant text-4xl font-semibold leading-[1.1] text-navy md:text-[48px]">
              Eight controls. Labelled by real status.
            </h2>
            <p className="mt-5 max-w-2xl font-dmsans text-lg font-light text-slateink">
              Six are active in production today; two are on a dated roadmap. We label each one so
              your evaluators never have to guess.
            </p>
          </FadeUp>
          <Stagger className="mt-14 grid grid-cols-2 gap-px overflow-hidden border-[0.5px] border-navy/15 lg:grid-cols-4">
            {BADGES.map((b) => (
              <StaggerItem key={b.title} className="bg-navy p-8 text-center">
                <b.icon className="mx-auto size-8 text-gold" strokeWidth={1.25} aria-hidden />
                <p className="mt-5 font-dmmono text-[11px] uppercase tracking-[0.2em] text-gold">
                  {b.label}
                </p>
                <h3 className="mt-2 font-cormorant text-xl font-normal text-offwhite">{b.title}</h3>
                <div className="mt-2">
                  <Status kind={b.status} />
                </div>
                <p className="mt-4 font-dmsans text-[13px] font-light leading-relaxed text-offwhite/60">
                  {b.desc}
                </p>
              </StaggerItem>
            ))}
          </Stagger>
        </div>
      </section>

      {/* SECTION 3 — ENCRYPTION DEEP DIVE */}
      <section className="py-24 md:py-section">
        <div className="mx-auto w-full max-w-container px-6 md:px-10">
          <FadeUp>
            <Overline>Encryption Architecture</Overline>
            <h2 className="mt-6 max-w-3xl font-cormorant text-3xl font-light leading-[1.1] text-offwhite md:text-[52px]">
              Data protected at every layer — at rest, in transit, and at the key.
            </h2>
          </FadeUp>
          <Stagger className="mt-14 grid grid-cols-1 gap-6 lg:grid-cols-3">
            {ENCRYPTION.map((c) => (
              <StaggerItem key={c.title}>
                <div
                  className="flex h-full flex-col border-[0.5px] border-gold/25 bg-navy-card p-8"
                  style={{ borderRadius: 2 }}
                >
                  <h3 className="font-cormorant text-2xl font-normal text-offwhite">{c.title}</h3>
                  <p className="mt-4 flex-1 font-dmsans text-[15px] font-light leading-relaxed text-offwhite/70">
                    {c.body}
                  </p>
                  <p className="mt-6 border-t border-gold/20 pt-5 font-dmmono text-[11px] leading-relaxed tracking-wide text-gold">
                    {c.tech}
                  </p>
                </div>
              </StaggerItem>
            ))}
          </Stagger>
        </div>
      </section>

      {/* SECTION 4 — ACCESS CONTROL */}
      <section className="bg-offwhite py-24 text-navy md:py-section">
        <div className="mx-auto w-full max-w-container px-6 md:px-10">
          <FadeUp>
            <Overline light>Access Control Architecture</Overline>
            <h2 className="mt-6 max-w-3xl font-cormorant text-4xl font-semibold leading-[1.1] text-navy md:text-[44px]">
              Who can access what — enforced at the database, not the application.
            </h2>
          </FadeUp>
          <FadeUp delay={0.08}>
            <div
              className="mt-10 border-l-2 border-gold bg-navy p-8 md:p-10"
              style={{ borderRadius: 2 }}
            >
              <p className="font-cormorant text-xl font-light italic leading-relaxed text-offwhite/90 md:text-[22px]">
                The most common security failure in multi-tenant SaaS is application-layer access
                control — where a compromised session can cross organisational boundaries by
                exploiting application logic. BaytyAI enforces data isolation at the PostgreSQL
                query layer via Row Level Security. A compromised application session cannot return
                another organisation’s data, because the database engine rejects the query before
                executing it.
              </p>
            </div>
          </FadeUp>
          <div className="mt-8 grid grid-cols-1 gap-6 md:grid-cols-2">
            <FadeUp>
              <div
                className="h-full border-l-2 bg-white p-8"
                style={{ borderLeftColor: '#7A1F1F', borderRadius: 2 }}
              >
                <p className="font-dmmono text-[11px] uppercase tracking-[0.28em] text-[#7A1F1F]">
                  Standard multi-tenant
                </p>
                <ul className="mt-6 flex flex-col gap-4">
                  {RLS_STANDARD.map((l) => (
                    <li
                      key={l}
                      className="flex items-start gap-2.5 font-dmsans text-[14px] font-light leading-relaxed text-slateink"
                    >
                      <span className="mt-0.5 text-[#7A1F1F]">✕</span> {l}
                    </li>
                  ))}
                </ul>
              </div>
            </FadeUp>
            <FadeUp delay={0.1}>
              <div
                className="h-full border-l-2 border-gold bg-navy p-8"
                style={{ borderRadius: 2 }}
              >
                <p className="font-dmmono text-[11px] uppercase tracking-[0.28em] text-gold">
                  BaytyAI Row Level Security
                </p>
                <ul className="mt-6 flex flex-col gap-4">
                  {RLS_BAYTY.map((l) => (
                    <li
                      key={l}
                      className="flex items-start gap-2.5 font-dmsans text-[14px] font-light leading-relaxed text-offwhite/80"
                    >
                      <span className="mt-0.5 text-gold">✓</span> {l}
                    </li>
                  ))}
                </ul>
              </div>
            </FadeUp>
          </div>

          {/* Role matrix */}
          <FadeUp delay={0.12}>
            <div className="mt-10 overflow-x-auto border-[0.5px] border-navy/15">
              <table className="w-full min-w-[720px] border-collapse text-left">
                <thead>
                  <tr className="bg-navy text-offwhite">
                    <th className="p-4 font-dmmono text-[10px] uppercase tracking-[0.14em]">
                      Role
                    </th>
                    {MATRIX_COLS.map((c) => (
                      <th
                        key={c}
                        className="p-4 text-center font-dmmono text-[10px] uppercase tracking-[0.14em]"
                      >
                        {c}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {ROLES.map((r, i) => (
                    <tr key={r} className={i % 2 ? 'bg-white' : 'bg-navy/[0.03]'}>
                      <td className="p-4 font-dmsans text-sm font-medium text-navy">{r}</td>
                      {MATRIX[i].map((c, j) => (
                        <td key={j} className="p-4 text-center font-dmmono text-sm">
                          {cellMark(c)}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </FadeUp>
        </div>
      </section>

      {/* SECTION 5 — HTTP HEADERS */}
      <section className="py-24 md:py-section">
        <div className="mx-auto w-full max-w-container px-6 md:px-10">
          <FadeUp>
            <Overline>HTTP Security Headers</Overline>
            <h2 className="mt-6 font-cormorant text-3xl font-light leading-[1.1] text-offwhite md:text-[44px]">
              Six headers. Five enforcing, one in report-only.
            </h2>
            <p className="mt-5 max-w-2xl font-dmsans text-base font-light text-offwhite/65">
              Security headers are configured in next.config and applied to every response. We show
              the real status of each — including the CSP, which runs in Report-Only while we tune
              it.
            </p>
          </FadeUp>
          <Stagger className="mt-12 flex flex-col divide-y divide-gold/15 border-y border-gold/15">
            {HEADERS.map((h) => (
              <StaggerItem key={h.name}>
                <div className="grid grid-cols-1 gap-2 py-6 md:grid-cols-12 md:gap-4">
                  <div className="md:col-span-3">
                    <p className="font-dmmono text-[13px] text-offwhite">{h.name}</p>
                    <div className="mt-1">
                      <Status kind={h.status} />
                    </div>
                  </div>
                  <p className="font-dmmono text-[12px] text-gold md:col-span-4">{h.value}</p>
                  <p className="font-dmsans text-[14px] font-light leading-relaxed text-offwhite/60 md:col-span-5">
                    {h.desc}
                  </p>
                </div>
              </StaggerItem>
            ))}
          </Stagger>
        </div>
      </section>

      {/* SECTION 6 — VERIFICATION DOCUMENT SECURITY */}
      <section className="bg-offwhite py-24 text-navy md:py-section">
        <div className="mx-auto w-full max-w-container px-6 md:px-10">
          <FadeUp>
            <Overline light>Verification Document Handling</Overline>
            <h2 className="mt-6 max-w-3xl font-cormorant text-4xl font-semibold leading-[1.1] text-navy md:text-[44px]">
              Identity documents are the highest-risk data on the platform. They are treated
              accordingly.
            </h2>
            <p className="mt-6 max-w-3xl font-dmsans text-base font-light leading-relaxed text-slateink">
              BaytyAI handles Emirates IDs, Iqama cards, passports, DED trade licences, MOMAH
              contractor registrations, and professional certificates. These are sensitive personal
              data under UAE PDPL Federal Decree-Law No. 45/2021, Saudi Arabia PDPL, and GDPR
              Article 9. The controls below apply exclusively to this data category, in addition to
              all platform-wide encryption and access controls.
            </p>
          </FadeUp>
          <Stagger className="mt-12 flex flex-col gap-5">
            {DOC_CONTROLS.map((c, i) => (
              <StaggerItem key={c.title}>
                <div
                  className="flex gap-5 border-[0.5px] border-navy/15 bg-white p-6 md:p-7"
                  style={{ borderRadius: 2 }}
                >
                  <span className="font-dmmono text-lg text-gold">
                    {String(i + 1).padStart(2, '0')}
                  </span>
                  <div>
                    <h3 className="font-dmmono text-[12px] uppercase tracking-[0.18em] text-navy">
                      {c.title}
                    </h3>
                    <p className="mt-2 font-dmsans text-[15px] font-light leading-relaxed text-slateink">
                      {c.body}
                    </p>
                  </div>
                </div>
              </StaggerItem>
            ))}
          </Stagger>
        </div>
      </section>

      {/* SECTION 7 — SOC 2 ROADMAP */}
      <section className="py-24 md:py-section">
        <div className="mx-auto w-full max-w-container px-6 md:px-10">
          <FadeUp>
            <Overline>SOC 2 Type II Roadmap</Overline>
            <h2 className="mt-6 max-w-3xl font-cormorant text-3xl font-light leading-[1.1] text-offwhite md:text-[44px]">
              A specific certification timeline — not a general alignment statement.
            </h2>
            <p className="mt-5 max-w-2xl font-dmsans text-base font-light text-offwhite/65">
              SOC 2 Type II requires a minimum six-month continuous evidence period before the audit
              can be commissioned. This timeline reflects that requirement.
            </p>
          </FadeUp>
          <Stagger className="mt-14 grid grid-cols-1 gap-6 md:grid-cols-4">
            {TIMELINE.map((s) => (
              <StaggerItem key={s.q}>
                <div
                  className="h-full border-[0.5px] border-gold/25 bg-navy-card p-7"
                  style={{ borderRadius: 2 }}
                >
                  <p className="font-dmmono text-[11px] uppercase tracking-[0.16em] text-gold">
                    {s.q}
                  </p>
                  <h3 className="mt-4 font-cormorant text-xl font-normal text-offwhite">{s.t}</h3>
                  <p className="mt-3 font-dmsans text-[14px] font-light leading-relaxed text-offwhite/60">
                    {s.b}
                  </p>
                </div>
              </StaggerItem>
            ))}
          </Stagger>
          <FadeUp delay={0.1}>
            <p className="mt-10 max-w-3xl font-dmsans text-sm font-light leading-relaxed text-offwhite/50">
              ISO 27001 scope assessment will be conducted alongside SOC 2 evidence collection. ISO
              27001 certification will be evaluated based on enterprise client requirements in Year
              3.
            </p>
          </FadeUp>
        </div>
      </section>

      {/* SECTION 8 — DATA RESIDENCY */}
      <section className="bg-offwhite py-24 text-navy md:py-section">
        <div className="mx-auto w-full max-w-container px-6 md:px-10">
          <FadeUp>
            <Overline light>Data Residency</Overline>
            <h2 className="mt-6 font-cormorant text-4xl font-semibold leading-[1.1] text-navy md:text-[44px]">
              Where your data is stored — and how that changes as we scale.
            </h2>
          </FadeUp>
          <FadeUp delay={0.08}>
            <div className="mt-12 overflow-x-auto border-[0.5px] border-navy/15">
              <table className="w-full min-w-[720px] border-collapse text-left">
                <thead>
                  <tr className="bg-navy text-offwhite">
                    <th className="p-4 font-dmmono text-[10px] uppercase tracking-[0.14em]">
                      Region
                    </th>
                    <th className="p-4 font-dmmono text-[10px] uppercase tracking-[0.14em]">
                      Data types
                    </th>
                    <th className="p-4 font-dmmono text-[10px] uppercase tracking-[0.14em]">
                      Status
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {RESIDENCY.map((r, i) => (
                    <tr key={r.region} className={i % 2 ? 'bg-white' : 'bg-navy/[0.03]'}>
                      <td className="p-4 font-dmsans text-sm font-medium text-navy">{r.region}</td>
                      <td className="p-4 font-dmsans text-[13px] font-light text-slateink">
                        {r.data}
                      </td>
                      <td className="p-4 font-dmmono text-[11px] uppercase tracking-widest text-navy/70">
                        {r.status}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </FadeUp>
          <FadeUp delay={0.12}>
            <p className="mt-6 max-w-3xl font-dmsans text-sm font-light leading-relaxed text-slateink">
              Data residency configuration is available as part of enterprise implementation
              planning. Programs requiring residency outside default regions should contact
              enterprise@baytyai.com to discuss dedicated environment options.
            </p>
          </FadeUp>
        </div>
      </section>

      {/* SECTION 9 — FAQ ACCORDION */}
      <section className="py-24 md:py-section">
        <div className="mx-auto w-full max-w-3xl px-6 md:px-10">
          <FadeUp>
            <Overline>Security FAQ</Overline>
            <h2 className="mt-6 font-cormorant text-3xl font-light leading-[1.1] text-offwhite md:text-[44px]">
              What enterprise procurement asks — answered specifically.
            </h2>
          </FadeUp>
          <div className="mt-12 flex flex-col border-y border-gold/15">
            {FAQS.map((f, i) => {
              const isOpen = open === i;
              return (
                <div key={f.q} className="border-b border-gold/15 last:border-b-0">
                  <button
                    type="button"
                    onClick={() => setOpen(isOpen ? null : i)}
                    aria-expanded={isOpen}
                    className="flex w-full items-center justify-between gap-4 py-6 text-left"
                  >
                    <span className="font-dmsans text-base font-medium text-offwhite">{f.q}</span>
                    <ChevronDown
                      className={`size-5 shrink-0 text-gold transition-transform duration-300 ${isOpen ? 'rotate-180' : ''}`}
                      aria-hidden
                    />
                  </button>
                  <div
                    className={`grid transition-all duration-300 ${isOpen ? 'grid-rows-[1fr] pb-6' : 'grid-rows-[0fr]'}`}
                  >
                    <div className="overflow-hidden">
                      <p className="font-dmsans text-[15px] font-light leading-relaxed text-offwhite/65">
                        {f.a}
                      </p>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* SECTION 10 — ENTERPRISE CONTACT */}
      <section className="bg-offwhite py-24 text-navy md:py-section">
        <div className="mx-auto w-full max-w-container px-6 md:px-10">
          <FadeUp>
            <h2 className="max-w-3xl font-cormorant text-4xl font-semibold leading-[1.1] text-navy md:text-[44px]">
              Your security team has questions we are prepared to answer.
            </h2>
            <p className="mt-5 max-w-2xl font-dmsans text-lg font-light text-slateink">
              BaytyAI will provide security documentation, penetration-test results, data processing
              agreements, and sub-processor lists to qualified enterprise and government programs
              under NDA.
            </p>
          </FadeUp>
          <Stagger className="mt-12 grid grid-cols-1 gap-6 md:grid-cols-3">
            {[
              {
                icon: Mail,
                title: 'Security documentation',
                body: 'Request our security questionnaire response, penetration-test summary, sub-processor list, and DPA template.',
                subject: 'Security Documentation',
              },
              {
                icon: FileText,
                title: 'Data Processing Agreement',
                body: 'Request a Data Processing Agreement for your program. Available in English and Arabic.',
                subject: 'DPA Request',
              },
              {
                icon: Shield,
                title: 'Enterprise security review',
                body: 'For government and regulated-industry programs requiring a formal vendor security assessment.',
                subject: 'Security Review',
              },
            ].map((c) => (
              <StaggerItem key={c.title}>
                <a
                  href={`mailto:enterprise@baytyai.com?subject=${encodeURIComponent(c.subject)}`}
                  className="flex h-full flex-col border-[0.5px] border-navy/15 bg-navy p-8 transition-colors hover:border-gold/50"
                  style={{ borderRadius: 2 }}
                >
                  <c.icon className="size-6 text-gold" strokeWidth={1.25} aria-hidden />
                  <h3 className="mt-6 font-dmsans text-lg font-medium text-offwhite">{c.title}</h3>
                  <p className="mt-3 flex-1 font-dmsans text-[14px] font-light leading-relaxed text-offwhite/60">
                    {c.body}
                  </p>
                  <span className="mt-6 font-dmmono text-[11px] uppercase tracking-[0.14em] text-gold">
                    enterprise@baytyai.com →
                  </span>
                </a>
              </StaggerItem>
            ))}
          </Stagger>
        </div>
      </section>
    </LuxShell>
  );
}
